{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

{{- if and .Values.tls.certData .Values.tls.keyData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.certificateSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certData }}
  tls.key: {{ .Values.tls.keyData }}
{{- end }}

{{- if .Values.tls.caCertData }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-ca-certificates
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.tls.caCertFileName }}: {{ .Values.tls.caCertData }}
{{- end }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: terraform-enterprise-env-secrets
  namespace: {{ .Release.Namespace }}
data:
{{- include "helpers.list-env-secrets" . | indent 2 }}
{{- if .Values.env.secretsFilePath }}
{{- include "helpers.enc-b64-secrets-file" . | indent 2 }}
{{- end }}

{{- if .Values.kubeconfig }}
{{- $clusterName := .Values.kubeconfig.clusterName }}
{{- $apiServer := .Values.kubeconfig.apiServer }}
{{- $caData := .Values.kubeconfig.caData }}
{{- $token := .Values.kubeconfig.token }}
{{- $namespace := .Values.kubeconfig.namespace | default "default" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-enterprise-kubeconfig
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  kubeconfig: {{ b64enc (printf "apiVersion: v1\nkind: Config\nclusters:\n- cluster:\n    certificate-authority-data: %s\n    server: %s\n  name: %s\ncontexts:\n- context:\n    cluster: %s\n    namespace: %s\n    user: %s\n  name: %s-context\ncurrent-context: %s-context\nusers:\n- name: %s\n  user:\n    token: %s\n" $caData $apiServer $clusterName $clusterName $namespace $clusterName $clusterName $clusterName $clusterName $token) | quote }}
{{- end }}
