apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-enterprise-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
